In [6]:
#assignment 1 Day 3
import numpy as np
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[4,5,6,7,8]
arr=np.array([list1,list2,list3])
print(arr)
arr[1:,2:5]

[[1 2 3 4 5]
 [2 3 4 5 6]
 [4 5 6 7 8]]


array([[4, 5, 6],
       [6, 7, 8]])

In [23]:
#assignment 2
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5, 4),columns=list('ABCD'))
print(df)
operation1=df.head()
operation2=df.isnull()
operation3=df['A'].value_counts()
operation4=df['C'].unique()
operation5=df.info()
operation6=df.describe()
print("\nOpertaion-1")
print(operation1)
print("\nOpertaion-2")
print(operation2)
print("\nOpertaion-3")
print(operation3)
print("\nOpertaion-4")
print(operation4)
print("\nOpertaion-5")
print(operation5)
print("\nOpertaion-6")
print(operation6)


          A         B         C         D
0  0.210287  0.405730 -0.256015  0.706557
1  1.472817 -0.836370 -1.890765 -0.346267
2 -0.880165 -1.241861  0.679949  0.106962
3 -0.370945  0.428241 -0.516937 -0.617100
4 -0.043569  0.641372 -0.791958  1.382008
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       5 non-null      float64
 1   B       5 non-null      float64
 2   C       5 non-null      float64
 3   D       5 non-null      float64
dtypes: float64(4)
memory usage: 288.0 bytes

Opertaion-1
          A         B         C         D
0  0.210287  0.405730 -0.256015  0.706557
1  1.472817 -0.836370 -1.890765 -0.346267
2 -0.880165 -1.241861  0.679949  0.106962
3 -0.370945  0.428241 -0.516937 -0.617100
4 -0.043569  0.641372 -0.791958  1.382008

Opertaion-2
       A      B      C      D
0  False  False  False  False
1  False  False  False  False
2  False  Fal